- name: Build Ignite from source
  hosts: all

  tasks:

    - name: add Ignite group
      become: yes
      become_user: root
      group: name=ignite state=present

    - name: add Ignite user
      become: yes
      become_user: root
      user: name={{ user }} password={{ password }} comment="Ignite user" group=ignite home=/home/ignite

    - name: create /home/ignite on behalf of {{ user }}
      become: yes
      become_user: root
      file: path=/home/ignite state=directory owner={{ user }}

    - name: get Ignite
      get_url:
        url: http://apache-mirror.rbc.ru/pub/apache//ignite/2.1.0/apache-ignite-2.1.0-src.zip
        dest: /home/src

    - unarchive:
        src: /home/src/apache-ignite-2.1.0-src.zip
        dest: /home/src
        remote_src: yes

    # XXX 
    - name: build Ignite
      command: /opt/apache-maven-3.5.0/bin/mvn clean package -DskipTests
      args:
        chdir: /home/src/apache-ignite-2.1.0-src
      environment:
        JAVA_HOME: /usr/lib/jvm/java-8-oracle
      register: out

    - debug: var=out.stdout_lines

    - name: here
      template:
        src: ./ignite.sh.j2
        dest: /etc/profile.d/ignite.sh
